### ISSUE TITLE
Route action as effect (react-router-redux)

### ISSUE THREAD

**Issue by mauron85** [raisemarketplace/redux-loop#28]
Hi, I'm struggling with making effects work with react-router-redux. I've setup react-router-redux routerMiddleware and trying to change history as effect.

Example:

``` javascript
import { push } from 'react-router-redux';

function reducer(state, action) {
  switch(action.type) {
  case 'FIRST_ACTION':
    return loop(
      state.set('firstRun', true),
      Effects.constant(push('/delivery'))
    );
}
```

In redux DevTools I see that action @@router/CALL_HISTORY_METHOD is triggered, but history (url) is not changed. Trying to figure out, what I'm doing wrong here.

**Comment by mauron85** [comment]
Example repo: https://github.com/mauron85/redux-loop-react-router-redux

**Comment by lukewestby** [comment]
@mauron85 so I'm not sure why this is the case, but this is entirely dependent on the order the enhancers are applied in. If you apply them in this order:

```js
const createPersistentStore = compose(
  install(),
  applyMiddleware(
    reduxRouterMiddleware
  ),
  DevTools.instrument()
)(createStore);
```

then everything works. Any other configuration either seems to break react-router-redux or otherwise actions returned by a `loop` are somehow not being handed to the middleware. I'm not sure why that's the case but I'll look into it more.

**Comment by mauron85** [comment]
@lukewestby thank you very much, changing order did the trick for me.

**Comment by lukewestby** [comment]
So it looks like because the redux-loop enhancer calls dispatch on the store that was created in the enhancers that follow it it effectively skips any dispatch enhancement that was applied by enhancers before it in the chain. In this case, `applyMiddleware` applied before redux-loop's enhancer doesn't allow redux-loop's `dispatch` to "know" about the custom dispatching that happens in order to enact middleware. This is why the first action makes it into the middleware but any actions that come from loops are ignored. This seems to be a concern with the way store enhancers work at a more fundamental level than a bug with redux-loop as it were.

@gaearon, if you have some time would you be able to weigh in?

**Comment by claudiuandrei** [comment]
@lukewestby from what I can see the actual issue is that the dispatch in redux-loop will actually trigger the effect. Combine will call the enhancers in reverse orders, so when dispatch is getting the state the effect was not actually created yet, as it will be in the applyMiddleware.

In the current implementation solution is to always have redux-loop at the beginning. A possible fix is to schedule the reading in dispatch so it will run the effects after the current event loop finishes.

**Comment by mauron85** [comment]
@lukewestby I've just upgraded to redux-loop 2.0.0 from 1.1.0 and it seems to store state very differently.
In version 1.1.0 state atom is object with structure:
```
state: {
model: {}
effect: {}
}
```
in 2.0.0 state is array
```
state: [
 0: {}
 1: {}
]
```
You can still use my example to reproduce.
Is this intended?

**Comment by lukewestby** [comment]
@mauron85 it is! It's intended to assist with destructuring when you call a reducer directly. Instead of doing

```javascript
{ model: m, effect: e } = reducer(state, action);
```
 you can just do
```javascript
[m, e] = reducer(state, action);
```

This was the reason for the major version bump.

**Comment by mocheng** [comment]
This thread of discussion saves me hours.

I am combining *react-router-redux* and *redux-loop*. It always fails with below message.

> Uncaught Error: Expected the routing state to be available either as `state.routing` or as the custom expression you can specify as `selectLocationState` in the `syncHistoryWithStore()` options. Ensure you have added the `routerReducer` to your store's reducers via `combineReducers` or whatever method you use to isolate your reducers

It looks that *redux-loop* changes the behavior of `store.getState` to return a array instead of object. 

Putting `install(()` ahead of `applyMiddleware` solves the problem.

```
  var storeEnhancers = compose(
    install(),
    applyMiddleware(promiseMiddleware, thunk)
  );
  
 const store = createStore(
    loopCombineReducers(allReducers),
    initialState,
    storeEnhancers
 )
```
