### ISSUE TITLE
Conflict between install() and devToolsExtension's store enhancer

### ISSUE THREAD

**Issue by jgoux** [raisemarketplace/redux-loop#39]
Hello,
I'm trying to use the [redux devtools extension](https://github.com/zalmoxisus/redux-devtools-extension) with redux-loop.
I don't think they play well together because as soon as the devToolsExtension enhancer is called, the state is of the shape `[state, effect]` which shouldn't happen when having `install()` called first.

Here is my code : 
```js
  const middlewares = [
    // this should be redux-loop's getState which returns an object
    ({ getState }) => {
      return (next) => (action) => {
        console.log(getState())// [state, effect] :(
        return next(action)
      }
    }

  ]

  const store = createStore(
    (state = {}) => state,
    compose(
      applyMiddleware(...middlewares),
      global.devToolsExtension ? global.devToolsExtension() : s => s,
      install()
    )
  )
```

If I remove the devToolsExtension, the state is an object as expected and everything works fine.

**Comment by lukewestby** [comment]
This is a problem we're dealing with in a number of different scenarios. The way enhancers compose has a really negative impact on how reliably all of the enhancers work together. See #28 as another example. I'm going to close this because I don't think there's anything we can do about it in this project. If you discover something definitely leave another comment and we'll reopen.
