### ISSUE TITLE
Add an Effect for dispatching an unknown amount of actions

### ISSUE THREAD

**Issue by tarjei** [raisemarketplace/redux-loop#41]
Hi, I'm working on implementing file upload progress using redux-loop. 

My problem is observing progress events from the XHR object. How many of these there will be I will not know on beforehand. 

What I'm looking for is a way to dispatch a number of effects (i.e. actions) from within my single Effect.promise()

What I would like is not to have to pass the dispatch function into the file upload actions, but instead that Effect.promise provided a way to emit new effects. Would that be possible?

Was that understandable?

Regards,
Tarjei

**Comment by lukewestby** [comment]
My instinct tells me that you'd need a middleware to do this, but I'm checking with some folks in the Elm community to find out how they'd do it, just to be sure 🙂 I'll report back when I gather some suggestions for you!

**Comment by tarjei** [comment]
Interesting! I guess you're right wrt middleware, but I would love to see a nice solution :)

**Comment by AgentME** [comment]
I was thinking that this could be done nicely with an `Effects.observable` function that took an [es-observable object](https://github.com/zenparsing/es-observable). Observables are like promises but can ~~resolve~~ deliver multiple values over time and then announce when they have no more values. (You can also unsubscribe from an observable, and it can choose to stop delivering values early and release resources, like aborting a connection, but I'm not sure if there's a good place for that yet in redux-loop.)  There's at least one implementation of plain es-observables, and both RxJS and Kefir's streams implement the interface too. I'm not familiar with Elm, but I think observables are very similar to Elm signals (which I assume it probably solves this same issue with).

Then with `Effects.observable`, you could track the progress of a request like this:

```js
function requestActions(id, url) {
  return new Observable(observer => {
    const xhr = new XMLHttpRequest();

    xhr.onload = () => {
      observer.next({
        id, type: 'XHR_LOADED', status: xhr.status,
        responseText: xhr.responseText
      });
      observer.complete();
    };
    xhr.onerror = () => {
      observer.next({
        id, type: 'XHR_ERROR', status: xhr.status,
        responseText: xhr.responseText
      });
      observer.complete();
    };
    xhr.onprogress = event => {
      observer.next({
        id, type: 'XHR_PROGRESS',
        loaded: event.loaded, total: event.total
      });
    };
    
    xhr.open('GET', url);
    xhr.send();

    // Abort the request if everyone unsubscribes. Note that redux-loop doesn't
    // actually ever trigger this currently.
    return () => {
      xhr.abort();
    };
  });  
}

function reducer(state, action) {
  switch(action.type) {

  case 'XHR_START':
    return loop(
      state.set('xhr_running', true),
      Effects.observable(requestActions, action.id, action.url),
    );
  case 'XHR_PROGRESS':
  // ...
  }
}
```

**Comment by lukewestby** [comment]
So the conclusion here is that in Elm you would need a separate `Signal.Mailbox Action` to which you would send progress actions and then route those actions in via the `inputs` option on a `StartApp` config. Translated, to redux, you'll need a middleware so you have access to `dispatch()`.

I don't want to introduce higher-order reactivity effects like `Effects.observable` because they immediately degrade the predictability about where things are happening, when, and why. As apps become more complicated and the effects paths that actions create become longer it can be really difficult to understand what's going on if there are observables proceeding all over the place all sourced from different actions at different times.

The other issue with observables specifically is that even though you would expect an observable for xhr progress to complete when the request is finished, introducing an arbitrary observable effect has to account for all observables, and there can be observables that never complete. This leaves open the questions of how do we track observables created by an action that are still open, can they be manually closed, and how do we deal with an ever growing stack of running observables in response to a particular action. My preferred answer is just to disallow them entirely.

Let me know if any of this doesn't make sense and i'll be happy to answer with more detail!
