### ISSUE TITLE
Is `dispatch` returning promise breaking to existent application?

### ISSUE THREAD

**Issue by mocheng** [raisemarketplace/redux-loop#49]
If existent code depends on the fact of default `dispatch` returning action, then redux-loop dispatch behavior is breaking.

**Comment by lukewestby** [comment]
`dispatch` returning an action is not a guaranteed behavior, per http://redux.js.org/docs/api/Store.html#dispatch

For example, when you use `redux-thunk`, calls to `dispatch` will return the function dispatched by the store instead of the action or actions that the thunk actually dispatched itself.
