### ISSUE TITLE
Why is 'Effects' needed?

### ISSUE THREAD

**Issue by ashtonwar** [raisemarketplace/redux-loop#57]
`Effects` just seems like a way to obfuscate the API without achieving much. I've defined `loop` like this in my application to remove the overhead:

```js
import {loop as _loop, Effects} from 'redux-loop'

export const loop = (state, ...effects) =>
  _loop(state, Effects.batch(effects.map(e =>
    typeof e === 'function' ?
      Effects.promise(() => Promise.resolve(e())) :
    e ?
      Effects.constant(e) :
      Effects.none()
  )))
```

Which can be used like this:

```js
loop(
  state,
  action1,
  () => action2,
  () => new Promise(resolve => resolve(action3)),
  null,
)
```

Original:

```js
loop(
  state,
  Effects.batch([
    Effects.constant(action1),
    Effects.promise(() => Promise.resolve((() => action2)())),
    Effects.promise(() => new Promise(resolve => resolve(action3)))
    Effects.none()
  ])
)
```

Does anyone have any thoughts regarding this revised API?

Should I open a PR & implement it?

**Comment by bdwain** [comment]
I don't think that api covers the full set of functionality. The readme is a little behind. There are more effect types [here](https://github.com/raisemarketplace/redux-loop/blob/master/docs/ApiDocs.md), and they would get harder to implement without giving them identifiers,

for example, call has the same arguments as promise. Also, nested batches are not supported this way (though you could probably check for array type if you want). And then there's lift.

**Comment by lukewestby** [comment]
I'm agreed with @bdwain here, explicitly tagging effects allows for more flexibility with how they are handled, allows us to do nested effects via batches and `lift`, and also lets us do sanity checks in development mode so we can be sure the thing you're handing to `loop` is definitely an effect of some kind. I also think of the two usages you posted the one using the current API is more clear about what is actually happening as there isn't any implicit behavior.

Thanks for your thoughtful suggestion, though! It's very helpful to have folks in the community thinking about how to improve the redux ecosystem.

**Comment by ashtonwar** [comment]
@bdwain Not sure I necessarily understand what `Effects.lift` does. If my understanding is correct `combineReducers` achieves the same thing with the huge advantage that you don't need to introduce any new concepts.

I can't see how the `Effects` API adds flexibility, can you give an example of something that would be harder to do without it?

Only issue is sync dispatch, though this can be fixed at the library-level.

@lukewestby What do you mean by implicit behavior? There is no change in behavior. Originally you pass in (state, effects), now you pass in (state, effects) and get the same thing. If you're reasoning with semiotics you would perceive (object, effects) which is clearly off. This is an API only change.

I can't strongly differentiate between which API "feels" clearer, anyone that does should check their personal bias first. My goal is to increase the "value per unit of conceptual space" by shrinking the API. This feels equivalent to when Andy Grove told power-hungry managers at Intel "You are bieng judged based on `value created per employee you are responsible for`, not the `number of employees you are responsible for`".

You only need one sanity check to confirm an effect was passed to loop because everything is an effect (`arguments.length >= 2`).

**Comment by lukewestby** [comment]
> Not sure I necessarily understand what Effects.lift does. If my understanding is correct combineReducers achieves the same thing with the huge advantage of being a drop-in replacement.

`lift` allows you to nest the resulting action from some effect inside of a higher-order effect in order to arbitrarily compose larger reducers from smaller ones that produce effects. `combineReducers` does not do this.

> I can't see how the Effects API adds flexibility, can you give an example of something that would be harder to do without it?

Any higher-order effects functions like `lift` and `batch` are possible only by having an API with explicit functions. It's only coincidental that the wrapper for `batch` can be just an array. Anything else will need to have a custom wrapper.

> What do you mean by implicit behavior? There is no change in behavior. Originally you pass in (state, effects), now you pass in (state, effects) and get the same thing. If you're reasoning with semiotics you would perceive (object, effects) which is clearly off. This is an API only change.

Before `loop` accepted one state object and one effect, and now it accepts one state object and any amount of seemingly anything else, from the perspective of someone seeing the code for the first time. Any information about what's actually going on is now hidden inside of the implementation rather than explicitly in the usage.

> I can't strongly differentiate between which API "feels" clearer, anyone that does should check their personal bias first.

Then what advantage does this change bring?

> My goal is to increase the "value per unit of conceptual space" by shrinking the API. 

This doesn't shrink the API, it only hides it. There's no getting around the fact that with redux-loop, there are certain kinds of effects and you can return them from your reducer. Managed effects are a new concept for a lot of redux users and that can feel weird, but they are _the_ concept in this library. You need to understand them in order to use redux-loop effectively, and so I'd rather have them be explicit.

> You only need one sanity check to confirm an effect was passed to loop because everything is an effect (arguments.length >= 2).

I also want to be able to sanity check that anything that can create an effect is properly tagged so that we have the user's intentions available to us at whatever time it becomes appropriate to throw an error. If the user intended to use a promise effect but their function didn't return a promise, it'll be easier to communicate about properly using a function called `Effects.promise` than it will about the wider range of things you can pass to `loop` in your suggested API.

**Comment by ashtonwar** [comment]
Acknowledged, to try and understand higher-order effects I imagined two examples where it's impossible to know how many effects you must dispatch until after you've started evaluating them.

1. You have a data structure similar to a linked list, each node contains some data & a promise generator that resolves to the next node.
  * Concatenate all the data & dispatch the result
2. You have an array of graph nodes, each action updates *one* node. Each time a node updates it may update other connected nodes (up to x jumps away)
  * Dispatch updates to other nodes

I'm still not sure what `Effects.lift` does but are you telling me it can handle problems like this?

**Comment by ashtonwar** [comment]
Just as an FYI I created [redux-plus](https://github.com/ashtonwar/redux-plus), it has the same effects API described in this issue & adds selectors / dynamic reducers.
